import "./globals.css";
import MainLayout from "@/layout/MainLayout";
import NextAuthProvider from "@/providers/NextuthProvider";
import { yekan } from "src/Utils/fonts";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
          <MainLayout>{children}</MainLayout>
        </NextAuthProvider>
      </body>
    </html>
  );
}
